name = "FiniteDifferenceFormula"
uuid = "fc1124c1-9066-4ec6-b9ac-c409d23c4e6c"
authors = ["David Wang"]
version = "1.0.4"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RowEchelon = "af85af4c-bcd5-5d23-b03a-a909639aa875"

[compat]
julia = "1"
RowEchelon = "0.2.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
